import Image from 'next/image';
import Link from 'next/link';
import { BoltIcon, ChartBarIcon, SunIcon, HomeModernIcon, CheckCircleIcon } from '@heroicons/react/24/outline';
import dynamic from 'next/dynamic';

const InteractiveMap = dynamic(() => import('@/components/home/InteractiveMap'), {
    ssr: false,
    loading: () => (
        <div className="h-[600px] w-full bg-slate-50 flex flex-col items-center justify-center rounded-3xl animate-pulse border border-slate-100">
            <div className="w-12 h-12 border-4 border-amber-200 border-t-amber-500 rounded-full animate-spin mb-4"></div>
            <p className="text-slate-400 font-bold tracking-widest uppercase text-sm">Loading Region Map...</p>
        </div>
    )
});

export const metadata = {
    title: 'Punjab Projects | Divvy Solar',
    description: 'Empowering Punjab with clean, efficient solar energy solutions. Join the sustainable revolution.',
};

// ─────────────────────────────────────────────────────────────
// EXACTLY 137 verified Punjab installations from client data
// Image: punjab-updated.jpeg → 713 x 782 px
// Lon: 73.85E–76.95E | Lat: 29.55N–32.50N
// x% = (lon-73.85)/(76.95-73.85)*100
// y% = (32.50-lat)/(32.50-29.55)*100
// City counts: Ludhiana:33, Malerkotla:32, Sangrur:12,
//   Mohali:14, Amritsar:6, Govindgarh:6, Patiala:3,
//   Khanna:3, Fathgarh Shib:4, Bathinda:2, Barnala:2,
//   Jalandhar:2, Morinda:2, JakhalMandi:2, rest:1 each
// ─────────────────────────────────────────────────────────────
const PUNJAB_PROJECTS = [
    { id: "ldh-01", city: "Ludhiana – Aggar Nagar Enclave", state: "Punjab", x: "64.7%", y: "54%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Aggar%20Nagar%20Enclave%20Ludhiana%20Punjab" },
    { id: "ldh-02", city: "Ludhiana – Rajguru Nagar Aggar Nagar", state: "Punjab", x: "63.3%", y: "53.3%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Rajguru%20Nagar%20Aggar%20Nagar%20Ludhiana%20Punjab" },
    { id: "ldh-03", city: "Ludhiana – VPO Rachhin Raikot", state: "Punjab", x: "64.1%", y: "55.2%", capacity: "7.48 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2020", panelsInstalled: "23+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/VPO%20Rachhin%20Raikot%20Ludhiana%20Punjab" },
    { id: "ldh-04", city: "Ludhiana – Kalakh Majri Road Dehlon", state: "Punjab", x: "64.8%", y: "52.9%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Kalakh%20Majri%20Road%20Dehlon%20Ludhiana%20Punjab" },
    { id: "ldh-05", city: "Ludhiana – Jogi Majra Maloudh", state: "Punjab", x: "62.5%", y: "54.3%", capacity: "3.96 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "12+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Jogi%20Majra%20Maloudh%20Ludhiana%20Punjab" },
    { id: "ldh-06", city: "Ludhiana – Acropolis Industries Dhandari", state: "Punjab", x: "65.4%", y: "54.9%", capacity: "29 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "87+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Acropolis%20Industries%20Dhandari%20Ludhiana%20Punjab" },
    { id: "ldh-07", city: "Ludhiana – APLOM Industries Jaspal Bangur", state: "Punjab", x: "63.5%", y: "52.2%", capacity: "30 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "90+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/APLOM%20Industries%20Jaspal%20Bangur%20Ludhiana%20Punjab" },
    { id: "ldh-08", city: "Ludhiana – BS Jandu Steel Tibba Road (2022)", state: "Punjab", x: "63.1%", y: "55.7%", capacity: "12 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "36+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/BS%20Jandu%20Steel%20Tibba%20Road%20(2022)%20Ludhiana%20Punjab" },
    { id: "ldh-09", city: "Ludhiana – Sohal Industries Bondal Samrala", state: "Punjab", x: "66%", y: "53.3%", capacity: "40 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "120+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sohal%20Industries%20Bondal%20Samrala%20Ludhiana%20Punjab" },
    { id: "ldh-10", city: "Ludhiana – Sanjeev Bassi Farm GT Road Hussainpura", state: "Punjab", x: "62%", y: "53.2%", capacity: "50 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "150+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sanjeev%20Bassi%20Farm%20GT%20Road%20Hussainpura%20Ludhiana%20Punjab" },
    { id: "ldh-11", city: "Ludhiana – BS Jandu Steel Tibba Road (2024)", state: "Punjab", x: "65%", y: "56.1%", capacity: "12 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "36+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/BS%20Jandu%20Steel%20Tibba%20Road%20(2024)%20Ludhiana%20Punjab" },
    { id: "ldh-12", city: "Ludhiana – Suraj Parkash Kapoor", state: "Punjab", x: "64.7%", y: "51.7%", capacity: "8 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "24+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Suraj%20Parkash%20Kapoor%20Ludhiana%20Punjab" },
    { id: "ldh-13", city: "Ludhiana – Rajinder Singh Sunny Enclave Mohali", state: "Punjab", x: "61.8%", y: "55.3%", capacity: "8 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "24+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Rajinder%20Singh%20Sunny%20Enclave%20Mohali%20Ludhiana%20Punjab" },
    { id: "ldh-14", city: "Ludhiana – Harjinder Kaur Model Gram", state: "Punjab", x: "66.5%", y: "54.6%", capacity: "15 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "45+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Harjinder%20Kaur%20Model%20Gram%20Ludhiana%20Punjab" },
    { id: "ldh-15", city: "Ludhiana – Solutions Packaging Canal Road Tibba", state: "Punjab", x: "62.4%", y: "51.8%", capacity: "55 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "165+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Solutions%20Packaging%20Canal%20Road%20Tibba%20Ludhiana%20Punjab" },
    { id: "ldh-16", city: "Ludhiana – Rajinder Chugh New Deep Nagar", state: "Punjab", x: "63.6%", y: "56.8%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "30+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Rajinder%20Chugh%20New%20Deep%20Nagar%20Ludhiana%20Punjab" },
    { id: "ldh-17", city: "Ludhiana – Anil Kumar Jain Grand Villa Sukhmani", state: "Punjab", x: "66.2%", y: "52.1%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "30+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Anil%20Kumar%20Jain%20Grand%20Villa%20Sukhmani%20Ludhiana%20Punjab" },
    { id: "ldh-18", city: "Ludhiana – Anita Walia Flower Enclave", state: "Punjab", x: "61%", y: "53.9%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "30+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Anita%20Walia%20Flower%20Enclave%20Ludhiana%20Punjab" },
    { id: "ldh-19", city: "Ludhiana – Major Singh Atam Nagar", state: "Punjab", x: "66.2%", y: "56.1%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "30+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Major%20Singh%20Atam%20Nagar%20Ludhiana%20Punjab" },
    { id: "ldh-20", city: "Ludhiana – Kewal Singh Urban Estate Phase 1", state: "Punjab", x: "63.9%", y: "50.9%", capacity: "9.81 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "30+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Kewal%20Singh%20Urban%20Estate%20Phase%201%20Ludhiana%20Punjab" },
    { id: "ldh-21", city: "Ludhiana – Harpal Singh Saini Model House", state: "Punjab", x: "62%", y: "56.4%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "30+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Harpal%20Singh%20Saini%20Model%20House%20Ludhiana%20Punjab" },
    { id: "ldh-22", city: "Ludhiana – Raj Partap Singh Friends Colony Sahnewal", state: "Punjab", x: "67.2%", y: "53.6%", capacity: "7.92 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "24+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Raj%20Partap%20Singh%20Friends%20Colony%20Sahnewal%20Ludhiana%20Punjab" },
    { id: "ldh-23", city: "Ludhiana – Dalbir Singh Bholapur Rajgarh Fusion", state: "Punjab", x: "61.3%", y: "52.1%", capacity: "5 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "15+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Dalbir%20Singh%20Bholapur%20Rajgarh%20Fusion%20Ludhiana%20Punjab" },
    { id: "ldh-24", city: "Ludhiana – Balraj Verma VPO Ramgarh Chandigarh Rd", state: "Punjab", x: "64.7%", y: "57.3%", capacity: "7.56 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "23+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Balraj%20Verma%20VPO%20Ramgarh%20Chandigarh%20Rd%20Ludhiana%20Punjab" },
    { id: "ldh-25", city: "Ludhiana – Ajmer Singh Shimlapuri", state: "Punjab", x: "65.7%", y: "51%", capacity: "5 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "15+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Ajmer%20Singh%20Shimlapuri%20Ludhiana%20Punjab" },
    { id: "ldh-26", city: "Ludhiana – Wazir Chand Sood BRS Nagar Block D", state: "Punjab", x: "60.6%", y: "55.1%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "30+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Wazir%20Chand%20Sood%20BRS%20Nagar%20Block%20D%20Ludhiana%20Punjab" },
    { id: "ldh-27", city: "Ludhiana – Rajinder Arora Ashok Vihar", state: "Punjab", x: "67.3%", y: "55.5%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "30+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Rajinder%20Arora%20Ashok%20Vihar%20Ludhiana%20Punjab" },
    { id: "ldh-28", city: "Ludhiana – Gurpreet Singh Gill Road", state: "Punjab", x: "62.6%", y: "50.6%", capacity: "5 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "15+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Gurpreet%20Singh%20Gill%20Road%20Ludhiana%20Punjab" },
    { id: "ldh-29", city: "Ludhiana – Bhagwant Singh Basant Avenue", state: "Punjab", x: "62.7%", y: "57.5%", capacity: "5 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "15+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Bhagwant%20Singh%20Basant%20Avenue%20Ludhiana%20Punjab" },
    { id: "ldh-30", city: "Ludhiana – Bharat Bhushan Atam Nagar Haibowal", state: "Punjab", x: "67.4%", y: "52.2%", capacity: "3 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "9+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Bharat%20Bhushan%20Atam%20Nagar%20Haibowal%20Ludhiana%20Punjab" },
    { id: "ldh-31", city: "Ludhiana – R P Engineering Kohara Chandigarh Rd", state: "Punjab", x: "60.3%", y: "53%", capacity: "300 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "900+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/R%20P%20Engineering%20Kohara%20Chandigarh%20Rd%20Ludhiana%20Punjab" },
    { id: "ldh-32", city: "Ludhiana – Harkrishan Cold Store Rachhin (2024)", state: "Punjab", x: "66.1%", y: "57.3%", capacity: "100 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "300+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Harkrishan%20Cold%20Store%20Rachhin%20(2024)%20Ludhiana%20Punjab" },
    { id: "ldh-33", city: "Ludhiana – KLM Creations Indra Colony", state: "Punjab", x: "64.7%", y: "50.1%", capacity: "60 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2025", panelsInstalled: "180+", status: "Operational", image: "/ludhiana.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/KLM%20Creations%20Indra%20Colony%20Ludhiana%20Punjab" },
    { id: "mlk-34", city: "Malerkotla – VP Goyal Near Civil Hospital", state: "Punjab", x: "66.2%", y: "66.5%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2020", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/VP%20Goyal%20Near%20Civil%20Hospital%20Malerkotla%20Punjab" },
    { id: "mlk-35", city: "Malerkotla – Savita Goyal Som Sons Colony", state: "Punjab", x: "64.8%", y: "65.8%", capacity: "7.15 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2020", panelsInstalled: "22+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Savita%20Goyal%20Som%20Sons%20Colony%20Malerkotla%20Punjab" },
    { id: "mlk-36", city: "Malerkotla – Sanjiv Kumar Pandher Colony Thandi Sarak", state: "Punjab", x: "65.6%", y: "67.7%", capacity: "8.45 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2020", panelsInstalled: "26+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sanjiv%20Kumar%20Pandher%20Colony%20Thandi%20Sarak%20Malerkotla%20Punjab" },
    { id: "mlk-37", city: "Malerkotla – Ravinder Gupta Som Sons Colony", state: "Punjab", x: "66.4%", y: "65.4%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2020", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Ravinder%20Gupta%20Som%20Sons%20Colony%20Malerkotla%20Punjab" },
    { id: "mlk-38", city: "Malerkotla – Parshotam Lal", state: "Punjab", x: "63.9%", y: "66.8%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Parshotam%20Lal%20Malerkotla%20Punjab" },
    { id: "mlk-39", city: "Malerkotla – Kanta Rani Mahavir Nagar", state: "Punjab", x: "67%", y: "67.4%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Kanta%20Rani%20Mahavir%20Nagar%20Malerkotla%20Punjab" },
    { id: "mlk-40", city: "Malerkotla – Manoj Kumar", state: "Punjab", x: "65%", y: "64.7%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Manoj%20Kumar%20Malerkotla%20Punjab" },
    { id: "mlk-41", city: "Malerkotla – Rajeev Bansal Samsung Colony", state: "Punjab", x: "64.6%", y: "68.3%", capacity: "6.7 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "21+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Rajeev%20Bansal%20Samsung%20Colony%20Malerkotla%20Punjab" },
    { id: "mlk-42", city: "Malerkotla – Radhe Shyam Kinger Khan Avenue", state: "Punjab", x: "67.5%", y: "65.8%", capacity: "7 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "21+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Radhe%20Shyam%20Kinger%20Khan%20Avenue%20Malerkotla%20Punjab" },
    { id: "mlk-43", city: "Malerkotla – Naresh Kumar Railway Road Shastari Nagar", state: "Punjab", x: "63.4%", y: "65.6%", capacity: "6 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "18+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Naresh%20Kumar%20Railway%20Road%20Shastari%20Nagar%20Malerkotla%20Punjab" },
    { id: "mlk-44", city: "Malerkotla – Vee Kay Garments Club Chowk", state: "Punjab", x: "66.5%", y: "68.6%", capacity: "8 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "24+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Vee%20Kay%20Garments%20Club%20Chowk%20Malerkotla%20Punjab" },
    { id: "mlk-45", city: "Malerkotla – Bharat Bhushan Pandher Colony", state: "Punjab", x: "66.2%", y: "64.2%", capacity: "8 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "24+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Bharat%20Bhushan%20Pandher%20Colony%20Malerkotla%20Punjab" },
    { id: "mlk-46", city: "Malerkotla – Manvi Sales Naudha Rani Road", state: "Punjab", x: "63.3%", y: "67.8%", capacity: "10 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Manvi%20Sales%20Naudha%20Rani%20Road%20Malerkotla%20Punjab" },
    { id: "mlk-47", city: "Malerkotla – Jain Enterprises Naudha Rani Road", state: "Punjab", x: "68.1%", y: "67.1%", capacity: "10 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Jain%20Enterprises%20Naudha%20Rani%20Road%20Malerkotla%20Punjab" },
    { id: "mlk-48", city: "Malerkotla – New Janta Nursery Ludhiana Road", state: "Punjab", x: "63.9%", y: "64.3%", capacity: "10 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/New%20Janta%20Nursery%20Ludhiana%20Road%20Malerkotla%20Punjab" },
    { id: "mlk-49", city: "Malerkotla – Suraj Corporation Madevi Road", state: "Punjab", x: "65.1%", y: "69.3%", capacity: "8 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "24+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Suraj%20Corporation%20Madevi%20Road%20Malerkotla%20Punjab" },
    { id: "mlk-50", city: "Malerkotla – Jain Textile Old Lohtia Bazar", state: "Punjab", x: "67.7%", y: "64.6%", capacity: "15 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "45+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Jain%20Textile%20Old%20Lohtia%20Bazar%20Malerkotla%20Punjab" },
    { id: "mlk-51", city: "Malerkotla – Masjid Suleh Khan Hader Sairakh Road", state: "Punjab", x: "62.5%", y: "66.4%", capacity: "20 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "60+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Masjid%20Suleh%20Khan%20Hader%20Sairakh%20Road%20Malerkotla%20Punjab" },
    { id: "mlk-52", city: "Malerkotla – Al Falah School The Mall", state: "Punjab", x: "67.7%", y: "68.7%", capacity: "42 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "126+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Al%20Falah%20School%20The%20Mall%20Malerkotla%20Punjab" },
    { id: "mlk-53", city: "Malerkotla – Chand Industries Ludhiana Bye Pass", state: "Punjab", x: "65.4%", y: "63.3%", capacity: "35 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "105+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Chand%20Industries%20Ludhiana%20Bye%20Pass%20Malerkotla%20Punjab" },
    { id: "mlk-54", city: "Malerkotla – Vinod Kumar Inside Cotton Railway Road", state: "Punjab", x: "63.4%", y: "69%", capacity: "7.035 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "22+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Vinod%20Kumar%20Inside%20Cotton%20Railway%20Road%20Malerkotla%20Punjab" },
    { id: "mlk-55", city: "Malerkotla – Pushp Raj Jain Model Town", state: "Punjab", x: "68.8%", y: "66.1%", capacity: "8 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "24+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Pushp%20Raj%20Jain%20Model%20Town%20Malerkotla%20Punjab" },
    { id: "mlk-56", city: "Malerkotla – Sukhjeewan Dhir Dhuri Road", state: "Punjab", x: "62.7%", y: "64.6%", capacity: "8 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "24+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sukhjeewan%20Dhir%20Dhuri%20Road%20Malerkotla%20Punjab" },
    { id: "mlk-57", city: "Malerkotla – Sarvesh Kathuria VIP Colony", state: "Punjab", x: "66.3%", y: "69.9%", capacity: "6.03 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "19+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sarvesh%20Kathuria%20VIP%20Colony%20Malerkotla%20Punjab" },
    { id: "mlk-58", city: "Malerkotla – DR MP Garg Railway Road Opp Civil Hospital", state: "Punjab", x: "67.3%", y: "63.4%", capacity: "8.04 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "25+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/DR%20MP%20Garg%20Railway%20Road%20Opp%20Civil%20Hospital%20Malerkotla%20Punjab" },
    { id: "mlk-59", city: "Malerkotla – Jay Kay Sales Adampal Road Industrial", state: "Punjab", x: "62.1%", y: "67.6%", capacity: "30 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "90+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Jay%20Kay%20Sales%20Adampal%20Road%20Industrial%20Malerkotla%20Punjab" },
    { id: "mlk-60", city: "Malerkotla – Gulzar Shah Jamalpura", state: "Punjab", x: "68.8%", y: "68%", capacity: "7.63 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "23+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Gulzar%20Shah%20Jamalpura%20Malerkotla%20Punjab" },
    { id: "mlk-61", city: "Malerkotla – J Star Iron Industries Madevi Road", state: "Punjab", x: "64.1%", y: "63%", capacity: "40 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "120+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/J%20Star%20Iron%20Industries%20Madevi%20Road%20Malerkotla%20Punjab" },
    { id: "mlk-62", city: "Malerkotla – Baltej Singh", state: "Punjab", x: "64.2%", y: "70.1%", capacity: "5 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "15+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Baltej%20Singh%20Malerkotla%20Punjab" },
    { id: "mlk-63", city: "Malerkotla – Gurmail Kaur", state: "Punjab", x: "68.9%", y: "64.7%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Gurmail%20Kaur%20Malerkotla%20Punjab" },
    { id: "mlk-64", city: "Malerkotla – Munish Jain Loha Bazar", state: "Punjab", x: "61.7%", y: "65.5%", capacity: "7 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "21+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Munish%20Jain%20Loha%20Bazar%20Malerkotla%20Punjab" },
    { id: "mlk-65", city: "Malerkotla – Deepak Garg Railway Road", state: "Punjab", x: "67.7%", y: "69.9%", capacity: "8 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2025", panelsInstalled: "24+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Deepak%20Garg%20Railway%20Road%20Malerkotla%20Punjab" },
    { id: "sgr-66", city: "Sangrur – Gurdwara Singh Sabha Ahmedgarh", state: "Punjab", x: "64.9%", y: "76.5%", capacity: "10 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Gurdwara%20Singh%20Sabha%20Ahmedgarh%20Sangrur%20Punjab" },
    { id: "sgr-67", city: "Sangrur – Labh Singh Jitwal Kalan", state: "Punjab", x: "63.1%", y: "75.7%", capacity: "5.6 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "17+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Labh%20Singh%20Jitwal%20Kalan%20Sangrur%20Punjab" },
    { id: "sgr-68", city: "Sangrur – Bhawana Devi Samsung Colony", state: "Punjab", x: "64.1%", y: "78%", capacity: "8.13 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "25+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Bhawana%20Devi%20Samsung%20Colony%20Sangrur%20Punjab" },
    { id: "sgr-69", city: "Sangrur – Ajeev Ahluwalia Thandi Sadak", state: "Punjab", x: "65.1%", y: "75.1%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Ajeev%20Ahluwalia%20Thandi%20Sadak%20Sangrur%20Punjab" },
    { id: "sgr-70", city: "Sangrur – VPO Moonak Ward 11", state: "Punjab", x: "62.1%", y: "76.8%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/VPO%20Moonak%20Ward%2011%20Sangrur%20Punjab" },
    { id: "sgr-71", city: "Sangrur – Sukhdev Singh Jitwal Kalan", state: "Punjab", x: "65.8%", y: "77.6%", capacity: "2.97 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "9+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sukhdev%20Singh%20Jitwal%20Kalan%20Sangrur%20Punjab" },
    { id: "sgr-72", city: "Sangrur – Amrik Singh Jitwal Kalan", state: "Punjab", x: "63.4%", y: "74.3%", capacity: "3.96 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "12+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Amrik%20Singh%20Jitwal%20Kalan%20Sangrur%20Punjab" },
    { id: "sgr-73", city: "Sangrur – Ajay Kumar Patiala Road", state: "Punjab", x: "62.9%", y: "78.7%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Ajay%20Kumar%20Patiala%20Road%20Sangrur%20Punjab" },
    { id: "sgr-74", city: "Sangrur – Kanta Rani Mahavir Nagar Sangrur", state: "Punjab", x: "66.4%", y: "75.6%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Kanta%20Rani%20Mahavir%20Nagar%20Sangrur%20Sangrur%20Punjab" },
    { id: "sgr-75", city: "Sangrur – Vishal Aggarwal Railway Road", state: "Punjab", x: "61.5%", y: "75.5%", capacity: "9.72 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Vishal%20Aggarwal%20Railway%20Road%20Sangrur%20Punjab" },
    { id: "sgr-76", city: "Sangrur – Shiv Bhole Flour Mill VPO Balran", state: "Punjab", x: "65.2%", y: "79.1%", capacity: "151.62 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "455+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Shiv%20Bhole%20Flour%20Mill%20VPO%20Balran%20Sangrur%20Punjab" },
    { id: "sgr-77", city: "Sangrur – Salim Khan Mohalla Madina", state: "Punjab", x: "64.9%", y: "73.6%", capacity: "7.5 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "23+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Salim%20Khan%20Mohalla%20Madina%20Sangrur%20Punjab" },
    { id: "moh-78", city: "Mohali – Kitabo Devi Sunny Enclave Sec 125", state: "Punjab", x: "88.9%", y: "60.5%", capacity: "9.43 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2020", panelsInstalled: "29+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Kitabo%20Devi%20Sunny%20Enclave%20Sec%20125%20Mohali%20Punjab" },
    { id: "moh-79", city: "Mohali – Manjit Kaur Phase 3 Focal Point", state: "Punjab", x: "87%", y: "59.6%", capacity: "30 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "90+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Manjit%20Kaur%20Phase%203%20Focal%20Point%20Mohali%20Punjab" },
    { id: "moh-80", city: "Mohali – Metals And Metals Phase 8 Industrial", state: "Punjab", x: "88.1%", y: "62.1%", capacity: "30 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "90+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Metals%20And%20Metals%20Phase%208%20Industrial%20Mohali%20Punjab" },
    { id: "moh-81", city: "Mohali – Rajinder Singh Sunny Enclave Sec 123", state: "Punjab", x: "89.1%", y: "59%", capacity: "8 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "24+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Rajinder%20Singh%20Sunny%20Enclave%20Sec%20123%20Mohali%20Punjab" },
    { id: "moh-82", city: "Mohali – Beas Bhardwaj Ward 4 Kharar", state: "Punjab", x: "85.9%", y: "60.9%", capacity: "3 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "9+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Beas%20Bhardwaj%20Ward%204%20Kharar%20Mohali%20Punjab" },
    { id: "moh-83", city: "Mohali – Hari Parkash Sharma Phase 1", state: "Punjab", x: "89.9%", y: "61.7%", capacity: "3 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "9+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Hari%20Parkash%20Sharma%20Phase%201%20Mohali%20Punjab" },
    { id: "moh-84", city: "Mohali – CV Sharma Sector 70", state: "Punjab", x: "87.4%", y: "58.1%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/CV%20Sharma%20Sector%2070%20Mohali%20Punjab" },
    { id: "moh-85", city: "Mohali – Gurudwara Guru Granth Sahib Phase 1", state: "Punjab", x: "86.8%", y: "62.8%", capacity: "20 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "60+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Gurudwara%20Guru%20Granth%20Sahib%20Phase%201%20Mohali%20Punjab" },
    { id: "moh-86", city: "Mohali – RVL Poly Industries Saidpura (2023)", state: "Punjab", x: "90.6%", y: "59.5%", capacity: "156 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "468+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/RVL%20Poly%20Industries%20Saidpura%20(2023)%20Mohali%20Punjab" },
    { id: "moh-87", city: "Mohali – Madhu Bala Sahauran Kharar", state: "Punjab", x: "85.3%", y: "59.4%", capacity: "4.86 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "15+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Madhu%20Bala%20Sahauran%20Kharar%20Mohali%20Punjab" },
    { id: "moh-88", city: "Mohali – Rohit Takyar Gharuan SAS Nagar", state: "Punjab", x: "89.3%", y: "63.3%", capacity: "4.77 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "15+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Rohit%20Takyar%20Gharuan%20SAS%20Nagar%20Mohali%20Punjab" },
    { id: "moh-89", city: "Mohali – Manish Goel Ward 7 Kharar", state: "Punjab", x: "89%", y: "57.4%", capacity: "4.77 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "15+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Manish%20Goel%20Ward%207%20Kharar%20Mohali%20Punjab" },
    { id: "moh-90", city: "Mohali – BS Company Industrial Phase 1 SAS Nagar", state: "Punjab", x: "85.1%", y: "62.2%", capacity: "10 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/BS%20Company%20Industrial%20Phase%201%20SAS%20Nagar%20Mohali%20Punjab" },
    { id: "moh-91", city: "Mohali – Mangal Singh Sunny Enclave Sec 123", state: "Punjab", x: "91.4%", y: "61.3%", capacity: "8 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "24+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Mangal%20Singh%20Sunny%20Enclave%20Sec%20123%20Mohali%20Punjab" },
    { id: "asr-92", city: "Amritsar – Pram Singh Green Avenue", state: "Punjab", x: "34.1%", y: "29.5%", capacity: "9.9 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/amritsar.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Pram%20Singh%20Green%20Avenue%20Amritsar%20Punjab" },
    { id: "asr-93", city: "Amritsar – Ramesh Kumar Krishna Square", state: "Punjab", x: "32.9%", y: "28.9%", capacity: "9.9 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "30+", status: "Operational", image: "/amritsar.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Ramesh%20Kumar%20Krishna%20Square%20Amritsar%20Punjab" },
    { id: "asr-94", city: "Amritsar – White House Sultanwind Gate", state: "Punjab", x: "33.6%", y: "30.6%", capacity: "20 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "60+", status: "Operational", image: "/amritsar.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/White%20House%20Sultanwind%20Gate%20Amritsar%20Punjab" },
    { id: "asr-95", city: "Amritsar – Surinder Kumar Bros Tarn Taran Rd", state: "Punjab", x: "34.2%", y: "28.5%", capacity: "65 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2023", panelsInstalled: "195+", status: "Operational", image: "/amritsar.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Surinder%20Kumar%20Bros%20Tarn%20Taran%20Rd%20Amritsar%20Punjab" },
    { id: "asr-96", city: "Amritsar – Ess Aar Embroideries Majitha Byepass", state: "Punjab", x: "32.2%", y: "29.7%", capacity: "14 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "42+", status: "Operational", image: "/amritsar.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Ess%20Aar%20Embroideries%20Majitha%20Byepass%20Amritsar%20Punjab" },
    { id: "asr-97", city: "Amritsar – ALA Foodstuff Gilwali Tarn Taran Road", state: "Punjab", x: "34.8%", y: "30.3%", capacity: "19 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "57+", status: "Operational", image: "/amritsar.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/ALA%20Foodstuff%20Gilwali%20Tarn%20Taran%20Road%20Amritsar%20Punjab" },
    { id: "gov-98", city: "Govindgarh – Puran Chand Sec 4B Shasti Nagar", state: "Punjab", x: "80.1%", y: "62%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Puran%20Chand%20Sec%204B%20Shasti%20Nagar%20Govindgarh%20Punjab" },
    { id: "gov-99", city: "Govindgarh – Jagpal Talwar Sec 2 Adarsh Nagar", state: "Punjab", x: "78.9%", y: "61.4%", capacity: "7.87 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "24+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Jagpal%20Talwar%20Sec%202%20Adarsh%20Nagar%20Govindgarh%20Punjab" },
    { id: "gov-100", city: "Govindgarh – Suresh Kumar Mandi Gobindgarh", state: "Punjab", x: "79.6%", y: "63.1%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Suresh%20Kumar%20Mandi%20Gobindgarh%20Govindgarh%20Punjab" },
    { id: "gov-101", city: "Govindgarh – JTL Steels GT Road Khanna Side", state: "Punjab", x: "80.2%", y: "61%", capacity: "200 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "600+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/JTL%20Steels%20GT%20Road%20Khanna%20Side%20Govindgarh%20Punjab" },
    { id: "gov-102", city: "Govindgarh – Ravinder Kumar Mandi Gobindgarh", state: "Punjab", x: "78.2%", y: "62.2%", capacity: "10 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "30+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Ravinder%20Kumar%20Mandi%20Gobindgarh%20Govindgarh%20Punjab" },
    { id: "gov-103", city: "Govindgarh – Ishwar Cast Forge Focal Point", state: "Punjab", x: "80.8%", y: "62.8%", capacity: "200 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2025", panelsInstalled: "600+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Ishwar%20Cast%20Forge%20Focal%20Point%20Govindgarh%20Punjab" },
    { id: "pat-104", city: "Patiala – Kanta Goyal Pathak Vihar", state: "Punjab", x: "82.7%", y: "73.4%", capacity: "6 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2020", panelsInstalled: "18+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Kanta%20Goyal%20Pathak%20Vihar%20Patiala%20Punjab" },
    { id: "pat-105", city: "Patiala – Mumtaz Bano Bank Colony", state: "Punjab", x: "81.8%", y: "73%", capacity: "5 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "15+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Mumtaz%20Bano%20Bank%20Colony%20Patiala%20Punjab" },
    { id: "pat-106", city: "Patiala – Harvinder Kumar Jindal Azad Nagar", state: "Punjab", x: "82.4%", y: "74.1%", capacity: "6.3 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "19+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Harvinder%20Kumar%20Jindal%20Azad%20Nagar%20Patiala%20Punjab" },
    { id: "khn-107", city: "Khanna – Sandeep Fertilizers New Grain Market", state: "Punjab", x: "77.2%", y: "61.1%", capacity: "5.4 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "17+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sandeep%20Fertilizers%20New%20Grain%20Market%20Khanna%20Punjab" },
    { id: "khn-108", city: "Khanna – Steel Corporation Village Alour", state: "Punjab", x: "76.3%", y: "60.7%", capacity: "150 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2025", panelsInstalled: "450+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Steel%20Corporation%20Village%20Alour%20Khanna%20Punjab" },
    { id: "khn-109", city: "Khanna – Amba Steel GT Road Alour", state: "Punjab", x: "76.9%", y: "61.8%", capacity: "150 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2025", panelsInstalled: "450+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Amba%20Steel%20GT%20Road%20Alour%20Khanna%20Punjab" },
    { id: "fsg-110", city: "Fatehgarh Sahib – Narain Company GT Road Mansi Govindgarh", state: "Punjab", x: "82.1%", y: "63%", capacity: "45 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "135+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Narain%20Company%20GT%20Road%20Mansi%20Govindgarh%20Fatehgarh%20Sahib%20Punjab" },
    { id: "fsg-111", city: "Fatehgarh Sahib – Garden Valley School Village Sampli", state: "Punjab", x: "80.9%", y: "62.5%", capacity: "30 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "90+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Garden%20Valley%20School%20Village%20Sampli%20Fatehgarh%20Sahib%20Punjab" },
    { id: "fsg-112", city: "Fatehgarh Sahib – Shakti Sharma Nabha Road Amloh", state: "Punjab", x: "81.6%", y: "64%", capacity: "5 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "15+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Shakti%20Sharma%20Nabha%20Road%20Amloh%20Fatehgarh%20Sahib%20Punjab" },
    { id: "fsg-113", city: "Fatehgarh Sahib – Rakesh Kumar Gupta Sec 21C", state: "Punjab", x: "82.2%", y: "62.1%", capacity: "5 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "15+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Rakesh%20Kumar%20Gupta%20Sec%2021C%20Fatehgarh%20Sahib%20Punjab" },
    { id: "fsg-114", city: "Fatehgarh Sahib – Gopala Steel Rolling Mills GT Road", state: "Punjab", x: "80.3%", y: "63.2%", capacity: "200 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2025", panelsInstalled: "600+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Gopala%20Steel%20Rolling%20Mills%20GT%20Road%20Fatehgarh%20Sahib%20Punjab" },
    { id: "bth-115", city: "Bathinda – Jagdev Singh Mansa Road Kotshamir", state: "Punjab", x: "35.5%", y: "77%", capacity: "4.95 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "15+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Jagdev%20Singh%20Mansa%20Road%20Kotshamir%20Bathinda%20Punjab" },
    { id: "bth-116", city: "Bathinda – Rupinder Kaur Mansa Road Sushant City", state: "Punjab", x: "34.7%", y: "76.7%", capacity: "2.97 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "9+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Rupinder%20Kaur%20Mansa%20Road%20Sushant%20City%20Bathinda%20Punjab" },
    { id: "bar-117", city: "Barnala – Gurucharan Singh Double Phatak Dhuri", state: "Punjab", x: "55.3%", y: "72.6%", capacity: "4.95 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "15+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Gurucharan%20Singh%20Double%20Phatak%20Dhuri%20Barnala%20Punjab" },
    { id: "bar-118", city: "Barnala – Sadhna Singla Dhuri Road Malerkotla", state: "Punjab", x: "54.5%", y: "72.3%", capacity: "7 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "21+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sadhna%20Singla%20Dhuri%20Road%20Malerkotla%20Barnala%20Punjab" },
    { id: "jal-119", city: "Jalandhar – Jaksh Industries Bulandpur", state: "Punjab", x: "56.3%", y: "41%", capacity: "150 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "450+", status: "Operational", image: "/jalandhar.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Jaksh%20Industries%20Bulandpur%20Jalandhar%20Punjab" },
    { id: "jal-120", city: "Jalandhar – Johnson Metal Hoshiarpur Road", state: "Punjab", x: "55.5%", y: "40.7%", capacity: "7 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "21+", status: "Operational", image: "/jalandhar.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Johnson%20Metal%20Hoshiarpur%20Road%20Jalandhar%20Punjab" },
    { id: "mor-121", city: "Morinda – Garden Valley Educational Society", state: "Punjab", x: "83.4%", y: "51%", capacity: "25 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "75+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Garden%20Valley%20Educational%20Society%20Morinda%20Punjab" },
    { id: "mor-122", city: "Morinda – Garden Valley International School 7", state: "Punjab", x: "82.6%", y: "50.7%", capacity: "50 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "150+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Garden%20Valley%20International%20School%207%20Morinda%20Punjab" },
    { id: "trn-123", city: "Tarn Taran – KSP Fibre Sahib", state: "Punjab", x: "34.9%", y: "35%", capacity: "200 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "600+", status: "Operational", image: "/amritsar.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/KSP%20Fibre%20Sahib%20Tarn%20Taran%20Punjab" },
    { id: "trn-124", city: "Tarn Taran – Ramandeep Singh Poultry Farm", state: "Punjab", x: "34.1%", y: "34.7%", capacity: "8.91 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "27+", status: "Operational", image: "/amritsar.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Ramandeep%20Singh%20Poultry%20Farm%20Tarn%20Taran%20Punjab" },
    { id: "ahm-125", city: "Ahmedgarh – Parveen Kumar Yash Painter Street", state: "Punjab", x: "58.8%", y: "70.8%", capacity: "8 KW", type: "Residential", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2021", panelsInstalled: "24+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Parveen%20Kumar%20Yash%20Painter%20Street%20Ahmedgarh%20Punjab" },
    { id: "mac-126", city: "Machhiwara – Sarv Jan Sewa Village Bhattian", state: "Punjab", x: "78%", y: "53.3%", capacity: "25 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "75+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sarv%20Jan%20Sewa%20Village%20Bhattian%20Machhiwara%20Punjab" },
    { id: "sam-127", city: "Samrala – Sarv Jan Sewa Educational Society 3", state: "Punjab", x: "75.8%", y: "56.2%", capacity: "25 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "75+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sarv%20Jan%20Sewa%20Educational%20Society%203%20Samrala%20Punjab" },
    { id: "kha-128", city: "Khamano – Sarv Jan Sewa Educational Society 4", state: "Punjab", x: "81.2%", y: "58.9%", capacity: "25 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2022", panelsInstalled: "75+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sarv%20Jan%20Sewa%20Educational%20Society%204%20Khamano%20Punjab" },
    { id: "taj-129", city: "Tajoka – Gurudwara Dera Baba Punjab Singh Ji", state: "Punjab", x: "48.4%", y: "40.6%", capacity: "50 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "150+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Gurudwara%20Dera%20Baba%20Punjab%20Singh%20Ji%20Tajoka%20Punjab" },
    { id: "kap-130", city: "Kapurthala – Sohan Cold Storage Aujla Road", state: "Punjab", x: "49.6%", y: "37.9%", capacity: "100 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2025", panelsInstalled: "300+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Sohan%20Cold%20Storage%20Aujla%20Road%20Kapurthala%20Punjab" },
    { id: "hsp-131", city: "Hoshiarpur – Prithi Cold Storage Garhshankar", state: "Punjab", x: "66.7%", y: "32.8%", capacity: "70 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "210+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/Prithi%20Cold%20Storage%20Garhshankar%20Hoshiarpur%20Punjab" },
    { id: "der-132", city: "Derabassi – RVL Poly Industries Saidpura (2024)", state: "Punjab", x: "93.8%", y: "63.2%", capacity: "125 KW", type: "Industrial/Commercial", builder: "Divvy Solar EPC", builderRole: "Lead EPC Partner", completedYear: "2024", panelsInstalled: "375+", status: "Operational", image: "/mohali.jpeg", pinColor: "#FECB00", region: "Punjab", googleMapLink: "https://www.google.com/maps/search/RVL%20Poly%20Industries%20Saidpura%20(2024)%20Derabassi%20Punjab" },
];;;;

export default function PunjabProjectsPage() {
    return (
        <div className="bg-[#f8fafc] min-h-screen font-sans selection:bg-amber-500 selection:text-white">

            {/* HERO SECTION */}
            <section className="relative min-h-[calc(100vh-56px)] flex items-center overflow-hidden bg-[#050a14]">
                <Image src="/utility_hero_4k.png" alt="Punjab Solar Vision" fill priority sizes="100vw" className="object-cover object-center scale-105" quality={100} />
                <div className="absolute inset-0 z-10" style={{ background: `linear-gradient(105deg, rgba(5,10,20,0.95) 0%, rgba(5,10,20,0.85) 40%, rgba(5,10,20,0.40) 70%, rgba(5,10,20,0.1) 100%)` }} />
                <div className="absolute top-0 left-0 z-10 pointer-events-none" style={{ width: '500px', height: '500px', background: 'radial-gradient(ellipse at top left, rgba(254,203,0,0.07) 0%, transparent 65%)' }} />
                <div className="absolute top-0 left-0 z-20 h-[3px]" style={{ width: '45%', background: 'linear-gradient(to right, #FECB00, transparent)' }} />
                <div className="relative z-20 w-full max-w-7xl mx-auto px-6 sm:px-10 lg:px-20 py-24 pb-28 md:py-28 md:pb-32">
                    <div className="max-w-2xl">
                        <div className="inline-flex items-center gap-2.5 mb-8" style={{ background: 'rgba(254,203,0,0.08)', border: '1px solid rgba(254,203,0,0.25)', borderRadius: '100px', padding: '6px 16px' }}>
                            <span className="w-1.5 h-1.5 rounded-full bg-yellow-400" style={{ boxShadow: '0 0 6px rgba(254,203,0,0.8)' }} />
                            <span className="text-yellow-300/90 text-[10px] sm:text-[11px] font-bold tracking-[0.2em] uppercase">Punjab Coverage Area</span>
                        </div>
                        <h1 className="font-extrabold text-white mb-6" style={{ fontSize: 'clamp(2rem, 8vw, 3.6rem)', lineHeight: '1.1', letterSpacing: '-0.5px', fontFamily: '"Georgia", serif', textShadow: '0 10px 30px rgba(0,0,0,0.5)' }}>
                            Powering Punjab's <br className="hidden sm:block" /> Solar Revolution
                        </h1>
                        <div className="mb-6" style={{ width: '50px', height: '3px', background: 'linear-gradient(to right, #FECB00, rgba(254,203,0,0.2))', borderRadius: '2px' }} />
                        <p className="text-white/90 font-normal mb-10" style={{ fontSize: '0.92rem', lineHeight: '1.8', maxWidth: '380px' }}>
                            Transforming the state's energy landscape with state-of-the-art, high-efficiency solar installations. We empower businesses, industries, and homes with independent, clean power.
                        </p>
                        <div className="flex items-center gap-4 flex-wrap">
                            <Link href="/contact" className="inline-flex justify-center items-center gap-2.5 font-bold text-sm px-7 py-3 rounded-full transition-all duration-300 hover:-translate-y-0.5 hover:brightness-110" style={{ background: 'linear-gradient(135deg, #FECB00 0%, #f5b800 100%)', color: '#0a0f1e', boxShadow: '0 4px 20px rgba(254,203,0,0.35)' }}>
                                Get a Free Quote
                            </Link>
                            <a href="#explore-projects" className="inline-flex justify-center items-center gap-2.5 font-bold text-sm px-7 py-3 rounded-full transition-all duration-300 hover:-translate-y-0.5" style={{ border: '1px solid rgba(255,255,255,0.2)', color: 'white', background: 'rgba(255,255,255,0.05)', backdropFilter: 'blur(10px)' }}>
                                View Projects
                            </a>
                        </div>
                    </div>
                </div>
            </section>

            {/* STATS BAR */}
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-12 -mt-8 md:-mt-12 relative z-30 mb-12 lg:mb-20">
                <div className="bg-white/70 backdrop-blur-2xl rounded-[2rem] shadow-[0_20px_50px_-12px_rgba(0,0,0,0.08)] px-6 py-8 md:px-12 md:py-10 border border-slate-100/80">
                    <div className="grid grid-cols-2 lg:grid-cols-4 gap-8 md:gap-12 divide-x-0 lg:divide-x divide-slate-100">
                        {[
                            { icon: CheckCircleIcon, val: "1000+", label: "Solar Projects Delivered", color: "text-amber-600", bg: "bg-amber-50" },
                            { icon: ChartBarIcon, val: "8+ Years", label: "EPC Experience", color: "text-blue-600", bg: "bg-blue-50" },
                            { icon: BoltIcon, val: "Across Punjab", label: "Execution Capability", color: "text-amber-600", bg: "bg-amber-50" },
                            { icon: SunIcon, val: "24/7", label: "Remote Monitoring Support", color: "text-amber-600", bg: "bg-amber-50" }
                        ].map((stat, idx) => (
                            <div key={idx} className="flex flex-col items-center lg:items-start lg:pl-10 first:pl-0 group">
                                <div className={`p-3.5 rounded-2xl ${stat.bg} mb-4 group-hover:scale-110 transition-transform duration-300 ${stat.color}`}>
                                    <stat.icon className="w-6 h-6" />
                                </div>
                                <h3 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight mb-1">
                                    {stat.val}
                                </h3>
                                <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest text-center lg:text-left leading-tight">{stat.label}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* CONTENT SECTION */}
            <div className="max-w-7xl mx-auto px-6 sm:px-8 lg:px-12 pb-10 lg:pb-16">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-stretch">
                    <div className="space-y-6 order-1 flex flex-col justify-center">
                        <div>
                            <span className="text-amber-600 font-bold tracking-[0.2em] uppercase text-xs mb-4 block flex items-center gap-2">
                                <span className="w-6 h-0.5 bg-amber-500 rounded-full"></span>
                                Why Punjab?
                            </span>
                            <h3 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-slate-900 leading-[1.1] tracking-tight" style={{ fontFamily: '"Georgia", serif' }}>
                                Solar Power for Punjab’s Homes & Industries
                            </h3>
                        </div>
                        <p className="text-base text-slate-700 leading-relaxed font-normal">
                            Punjab’s fast-growing industrial clusters and high electricity demand make solar a smart long-term investment. Divvy Solar delivers <strong className="text-slate-900 font-bold">turnkey solar EPC in Punjab</strong> for residential rooftops, commercial buildings, and industrial facilities, designed for strong generation, safe installation, and measurable savings across seasons.
                        </p>
                        <div className="space-y-3">
                            {[
                                { title: "PSPCL Net Metering Support", desc: "We assist with PSPCL net metering documentation and approvals, helping you connect your on-grid solar system smoothly and start saving faster." },
                                { title: "Subsidy Guidance (Where Applicable)", desc: "Our team guides you through eligibility and documentation for applicable solar subsidies, helping reduce upfront costs and improve ROI." }
                            ].map((feature, idx) => (
                                <div key={idx} className="flex gap-4 p-4 rounded-xl bg-white border border-slate-100 shadow-sm hover:shadow-md transition-all duration-300 group">
                                    <div className="flex-shrink-0 mt-0.5">
                                        <div className="w-7 h-7 rounded-full bg-amber-50 flex items-center justify-center group-hover:bg-amber-500 transition-colors duration-300">
                                            <CheckCircleIcon className="w-4 h-4 text-amber-600 group-hover:text-white transition-colors duration-300" />
                                        </div>
                                    </div>
                                    <div>
                                        <h4 className="font-bold text-base text-slate-900 mb-0.5">{feature.title}</h4>
                                        <p className="text-slate-600 text-sm leading-relaxed font-normal">{feature.desc}</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                    <div className="order-2 relative h-full min-h-[400px]">
                        <div className="relative h-full w-full rounded-2xl overflow-hidden shadow-xl group">
                            <Image src="/utility_intro_4k.png" alt="Punjab Solar Focus" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition-transform duration-1000 group-hover:scale-105" quality={100} />
                        </div>
                    </div>
                </div>
            </div>

            {/* INTERACTIVE MAP */}
            <div id="explore-projects" className="bg-white pt-8 pb-16 lg:pt-12 lg:pb-24 border-t border-slate-100 relative">
                <div className="absolute inset-0 opacity-[0.03] pointer-events-none" style={{ backgroundImage: 'radial-gradient(#0f172a 1px, transparent 1px)', backgroundSize: '24px 24px' }}></div>
                <InteractiveMap
                    mapImage="/punjab-updated.jpeg"
                    customProjects={PUNJAB_PROJECTS}
                    title="Live Punjab Coverage"
                    subtitle="137 verified installations across <span class='font-black text-amber-600'>22+ cities in Punjab</span>. Click any pin for satellite view."
                    headerLabel="Live Project Coverage"
                />
            </div>

            {/* BOTTOM CTA */}
            <div className="max-w-7xl mx-auto px-6 pb-32 lg:pb-32">
                <div className="relative py-10 px-8 rounded-[2.5rem] overflow-hidden bg-[#0a0f1c] text-center border border-white/10 shadow-2xl">
                    <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(45,212,191,0.1),transparent_50%)]"></div>
                    <div className="relative z-10 flex flex-col items-center max-w-2xl mx-auto">
                        <h2 className="text-2xl md:text-3xl font-extrabold text-white mb-4 leading-tight" style={{ fontFamily: '"Georgia", serif' }}>
                            Ready to shrink your electricity bills?
                        </h2>
                        <p className="text-slate-400 mb-8 text-sm md:text-base max-w-lg">Join families and businesses across Punjab achieving energy independence.</p>
                        <Link href="/contact" className="inline-flex items-center justify-center px-8 py-3.5 text-[11px] font-bold tracking-[0.2em] uppercase text-[#02142B] bg-amber-400 rounded-full hover:bg-amber-300 hover:shadow-[0_0_30px_rgba(254,203,0,0.3)] transition-all duration-300 hover:-translate-y-1">
                            Get a Free Site Assessment
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    );
}